artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ParitoshVyawahare/Student-Performance-Azure-deployment/raw/refs/heads/main/archive%20(12).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
